### ISSUE TITLE
Error on `brew rmtree bokken'

### ISSUE THREAD

**Issue by ylluminarious** [beeftornado/homebrew-rmtree#18]
I tried uninstalling [`bokken`](http://bokken.re/) via `brew rmtree bokken` and wound up with the following stack trace:

```
==> Examining installed formulae required by bokken...
Error: undefined method `installed?' for #<PythonRequirement: "python" []> \
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `dependency_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:165:in `dependency_tree_as_keg_names'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:280:in `block in build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:100:in `show_wait_spinner'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:274:in `build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:335:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:393:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

Just as a sanity check, to make sure that running `rmtree` on other packages works alright, I did `brew install spark` and `brew rmtree spark` (using [`spark`](https://zachholman.com/spark/) simply because it is very small). Doing that worked fine:

```
==> Examining installed formulae required by spark...
 /

Can safely be removed
----------------------


Proceed?[y/N]: y
==> Cleaning up packages safe to remove

Uninstalling /usr/local/Cellar/spark/1.0.1... (6 files, 7.0KB)
```

I assume the above error is somehow specific to `bokken` because it uses Python internally, and that error mentions Python.

**Comment by beeftornado** [comment]
Thanks for the detailed report! I'll see what I can do

**Comment by anticitizen4** [comment]
I'm having a similar problem with `brew rmtree mps-youtube`:
```
==> Examining installed formulae required by mps-youtube...
 /Error: undefined method `installed?' for #<MinimumMacOSRequirement: "minimummacos" [:mountain_lion]>
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `dependency_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:165:in `dependency_tree_as_keg_names'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:280:in `block in build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:100:in `show_wait_spinner'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:274:in `build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:335:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:393:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

I, too, performed 'sanity check', `brew rmtree wget`:
```
==> Examining installed formulae required by wget...
 /

Can safely be removed
----------------------
openssl@1.1

Proceed?[y/N]:
```

But, `brew rmtree mysql`:
```
==> Examining installed formulae required by mysql...
 /Error: undefined method `installed?' for #<MinimumMacOSRequirement: "minimummacos" [:lion]>
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `dependency_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:165:in `dependency_tree_as_keg_names'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:280:in `block in build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:100:in `show_wait_spinner'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:274:in `build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:335:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:389:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:393:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

Hope this helps.

**Comment by SuyashLakhotia** [comment]
I'm having similar issues with `opencv` and `opencv3`.

```
$ brew rmtree opencv --dry-run
This is a dry-run, nothing will be deleted
==> Examining installed formulae required by opencv...
 /Error: undefined method `installed?' for #<PythonRequirement: "python" []>
/usr/local/bin/brew-rmtree.rb:160:in `select'
/usr/local/bin/brew-rmtree.rb:160:in `dependency_tree'
/usr/local/bin/brew-rmtree.rb:166:in `dependency_tree_as_keg_names'
/usr/local/bin/brew-rmtree.rb:281:in `block in build_tree'
/usr/local/bin/brew-rmtree.rb:101:in `show_wait_spinner'
/usr/local/bin/brew-rmtree.rb:275:in `build_tree'
/usr/local/bin/brew-rmtree.rb:336:in `rmtree'
/usr/local/bin/brew-rmtree.rb:391:in `block in main'
/usr/local/bin/brew-rmtree.rb:391:in `each'
/usr/local/bin/brew-rmtree.rb:391:in `main'
/usr/local/bin/brew-rmtree.rb:395:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

```
$ brew rmtree opencv3 --dry-run
This is a dry-run, nothing will be deleted
==> Examining installed formulae required by opencv3...
 /Error: undefined method `installed?' for #<PythonRequirement: "python" []>
/usr/local/bin/brew-rmtree.rb:160:in `select'
/usr/local/bin/brew-rmtree.rb:160:in `dependency_tree'
/usr/local/bin/brew-rmtree.rb:166:in `dependency_tree_as_keg_names'
/usr/local/bin/brew-rmtree.rb:281:in `block in build_tree'
/usr/local/bin/brew-rmtree.rb:101:in `show_wait_spinner'
/usr/local/bin/brew-rmtree.rb:275:in `build_tree'
/usr/local/bin/brew-rmtree.rb:336:in `rmtree'
/usr/local/bin/brew-rmtree.rb:391:in `block in main'
/usr/local/bin/brew-rmtree.rb:391:in `each'
/usr/local/bin/brew-rmtree.rb:391:in `main'
/usr/local/bin/brew-rmtree.rb:395:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:101:in `<main>'
```

**Comment by glukki** [comment]
Hey, take a look at #19 — it must fix the issue

**Comment by beeftornado** [comment]
Thanks everyone for the detailed reports, I just committed a fix.

**Comment by ylluminarious** [comment]
@beeftornado Thanks!
