### ISSUE TITLE
/Error: undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by heychirag** [beeftornado/homebrew-rmtree#20]
```
➜  ~ brew rmtree --dry-run mpv
This is a dry-run, nothing will be deleted
==> Examining installed formulae required by mpv...
 /Error: undefined method `name' for nil:NilClass
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:175:in `as_formula'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `block in dependency_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `map'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:159:in `dependency_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:166:in `dependency_tree_as_keg_names'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:287:in `block in build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:100:in `show_wait_spinner'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:281:in `build_tree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:342:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:396:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:396:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:396:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:400:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
➜  ~
```
Maybe a problem with my homebrew installation. Could you help me? Never ran into an error like this before.

**Comment by dangyuluo** [comment]
Same question. Can't find any answer.

**Comment by Jahhein** [comment]
Glad to find I wasn't the only one having this issue after I tried cleaning up my packages.

However I'm not glad I couldn't clean up with this great package! Ha.

**Comment by iliabenson** [comment]
Similar issue:

``` brew rmtree ghex
==> Examining installed formulae required by ghex...
 /Error: undefined method `installed?' for #<Python3Requirement: "python3" []>
Did you mean?  instance_of?
/usr/local/bin/brew-rmtree.rb:160:in `select'
/usr/local/bin/brew-rmtree.rb:160:in `dependency_tree'
/usr/local/bin/brew-rmtree.rb:166:in `dependency_tree_as_keg_names'
/usr/local/bin/brew-rmtree.rb:281:in `block in build_tree'
/usr/local/bin/brew-rmtree.rb:101:in `show_wait_spinner'
/usr/local/bin/brew-rmtree.rb:275:in `build_tree'
/usr/local/bin/brew-rmtree.rb:336:in `rmtree'
/usr/local/bin/brew-rmtree.rb:391:in `block in main'
/usr/local/bin/brew-rmtree.rb:391:in `each'
/usr/local/bin/brew-rmtree.rb:391:in `main'
/usr/local/bin/brew-rmtree.rb:395:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'```

**Comment by beeftornado** [comment]
Thanks for the report, investigating this now. Apologies for the delayed response.

**Comment by beeftornado** [comment]
Real sorry everyone. But I just fixed this. Give me a few minutes to push the change.
