### ISSUE TITLE
private method `named' called

### ISSUE THREAD

**Issue by ElfSundae** [beeftornado/homebrew-rmtree#35]
```console
$ brew rmtree php@7.2          
Error: private method `named' called for ["php@7.2"]:Array
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:507:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:535:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:82:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
$ brew --version
Homebrew 2.2.10
Homebrew/homebrew-core (git revision e03a7e; last commit 2020-03-10)
Homebrew/homebrew-cask (git revision 0f475; last commit 2020-03-11)
```

**Comment by beeftornado** [comment]
Thanks for reporting this. I'll try and find some time later this evening to fix it.

**Comment by beeftornado** [comment]
Apologies for not updating sooner. I've triaged the issue and I just need to update the `ARGV` parsing to match the current Homebrew standard. I will have a fix available in the next 24 hours.
