### ISSUE TITLE
Error: undefined method `args_includes_ignores' for Homebrew:Module

### ISSUE THREAD

**Issue by hsingll** [beeftornado/homebrew-rmtree#44]
`brew rmtree ffmpeg
Error: undefined method `args_includes_ignores' for Homebrew:Module
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:176:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:433:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:554:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:81:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:113:in `<main>'`

**Comment by beeftornado** [comment]
Can't repro
