### ISSUE TITLE
Unable to remove packages

### ISSUE THREAD

**Issue by Galaxy0419** [beeftornado/homebrew-rmtree#49]
It seems there are some errors in the scripts, when I remove packages using command ```brew rmtree [package]```, it shows an error.  Brew and rmtree are up to date.
```
Error: CLI arg for `include_build?` is not declared for this command
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:147:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/dependencies_helpers.rb:14:in `args_includes_ignores'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:176:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `all?'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `block in uses'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `select'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `uses'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:433:in `rmtree'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `block in main'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `each'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `main'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-rmtree/cmd/brew-rmtree.rb:554:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

**Comment by ljcucc** [comment]
+1, Same error message here:
```bash
$ brew rmtree qt

Error: CLI arg for `include_build?` is not declared for this command
/usr/local/Homebrew/Library/Homebrew/cli/args.rb:147:in `method_missing'
/usr/local/Homebrew/Library/Homebrew/dependencies_helpers.rb:14:in `args_includes_ignores'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:176:in `block (2 levels) in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `all?'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:133:in `block in uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `select'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:132:in `uses'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:433:in `rmtree'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `block in main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `each'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:550:in `main'
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:554:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:91:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:124:in `<main>'
```

**Comment by willbchang** [comment]
Seems like the author doesn't watch this repo, notification may not be received. I think it's better to make a pull request with fix and @ the author to check and merge it, if there is someone familiar with ruby and homebrew or have time to investigate them.

**Comment by ybbond** [comment]
@Galaxy0419 @ljcucc can you both give more information about your system? **Don't need to new comment, just edit the prev**.
The bug also happens to me, and I think for whoever know Ruby will be more encouraged to fix if more information given.

**Desktop:**
- **OS**
  macOS
- **OS version**
  11.2.3
- **homebrew version**
  Homebrew 3.0.10-32-gbfb9134
  Homebrew/homebrew-core (git revision b1794361d9; last commit 2021-03-29)
  Homebrew/homebrew-cask (git revision 4d84703265; last commit 2021-03-29)
- **terminal**
  kitty 0.19.3 created by Kovid Goyal
- **shell**
  zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by nitantsoni** [comment]
Getting this same error

Running Big Sur, 11.2.3 with Homebrew 3.0.10 on Fish shell

**Comment by beeftornado** [comment]
Hi all, I apologize for the lack of a response. I'm committed to helping fix things that are broken; anything else I would be happy to review contributions. Being that this looks broken, I'll dig into this in a few hours. Based on what you all have provided so far, it appears to be an API change, which shouldn't take too long once I familiarize myself with the current documentation.

**Comment by beeftornado** [comment]
Think this should be resolved now, thanks for all the info everyone
